name: CI/CD
on:
  push:
    branches: [ release, main ]
  pull_request:
    branches: [ release, main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@v2
       - uses: actions/setup-java@v2
         with:
         distribution: 'build'
         java-version: '17'

       - name: Grant execute
         run: chmod +x gradlew

       - name: Build
         run: |
           echo Build.
           ./gradlew clean build

       - name: Set artifact
         run: echo "artifact=$ (ls ./build/libs)" >> $GITHUB_ENV

       - name: Deploy to Lightsail
         uses: orderabbit/store24H-back@main
         with:
          script: |
            cd /home/ubuntu/store24H-front
            # 다음에 artifact 사용 가능
            echo $artifact
            cd /home/ubuntu/store24H-front
            echo $artifact
            sudo docker stop back-container
            sudo docker rm back-container
            sudo docker build -t tdb .
            sudo docker create --name back-container -p 80:8080 tdb:latest
            sudo docker start back-container
         
