name: CI/CD

on:
  push:
    branches: ['main', 'release']
  pull_request:
    branches: ['main', 'release']
    
env:
  LIGHTSAIL_SSH_KEY: ${{ secrets.LIGHTSAIL_SSH_KEY }}
  LIGHTSAIL_HOST: ${{ secrets.LIGHTSAIL_HOST }}
  LIGHTSAIL_USERNAME: bitnami
  AWS_REGION: ap-northeast-2

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'build'

      - name: 권한
        run: chmod +x gradlew

      - name: 빌드
        run: |
          ./gradlew clean build

      - name: AWS 인증하기
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ env.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Deploy to Lightsail
        uses: orderabbit/store24H-back@v1
        with:
          host: ${{ secrets.LIGHTSAIL_HOST }}
          username: ${{ secrets.LIGHTSAIL_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: '*'
          strip_components: 1
          target: '/home/ubuntu/{project-name}'
          script: |
            cd /home/ubuntu/store24H-back
            # 다음에 artifact 사용 가능
            sudo docker stop back-container
            sudo docker rm back-container
            sudo docker build -t tdb .
            sudo docker create --name back-container -p 80:4040 tdb:latest
            sudo docker start back-container
